### ISSUE TITLE
Database is mutated program during execution

### ISSUE THREAD

**Issue by gzaripov** [postmanlabs/mime-format#15]
```
 var result = db[mime] || module.exports.guess(mime);

// add the charset info to the mime.
result && charset && (result.charset = charset);
result && (result.source = mime); 
```
Here you set db object into result variable and in case when charset is present you assigning charset to it, but this object is still referenced from db. you need to copy result object and then assign charset to it.

**Comment by codenirvana** [comment]
Fixed in `v2.0.1`.
