### ISSUE TITLE
application/hal+json

### ISSUE THREAD

**Issue by benhamill** [postmanlabs/mime-format#2]
I notice that y'all've got `application/vnd.hal+json` and `application/vnd.hal+xml`, but a lot of services respond with simply `application/hal+json` or `application/hal+xml`. Could those be added?

**Comment by shamasis** [comment]
#1 should fix this. released in `0.2.0`. However, #3 going to v0.3.0 is much more fault tolerant with respect to server content type responses.

Essentially, we added a "guessing" logic if the entry is not in db. @benhamill.

**Comment by benhamill** [comment]
That's cool. Do you have an idea of what release of Postman (Mac app) its self those might get into?

**Comment by shamasis** [comment]
We are tackling two more issues - with localhost and client side SSL certificates. I am hoping we would roll out this change and one more this weekend or early next week.

Cc @numaanashraf

**Comment by shamasis** [comment]
It's out! 4.5.1 - would love if you could test and let us know if all cases are covered. @benhamill
